name: nlp_py38
channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.8
  - keras-preprocessing=1.1.2
  - transformers=4.14.1
  - tokenizers=0.10.3
  - spacy=3.4.1
  - pytorch=1.11.0
  - tensorflow=2.8.2
  - jupyterlab=3.4.5
  - ipywidgets=8.0.1
  - fasttext=0.9.2
  - spacy-model-en_core_web_md=3.4.0
  - pip
  - pip:
    - pandas==1.4.3
    - datasets==2.4.0
    - matplotlib==3.5.3
    - seaborn==0.11.2
    - plotly==5.10.0
    - scikit-learn==1.1.2
    - pyarrow==9.0.0
    - textdistance==4.4.0
    - gensim==4.2.0
    - nltk==3.7
    - wordcloud==1.8.2.2
    - lightgbm==3.3.2
    - pandarallel==1.6.3
    - xgboost==1.6.2
    - elasticsearch==8.3.3
    - contractions==0.1.72
    - plot-keras-history==1.1.37
    - sastrawi==1.0.1
    - optuna==3.0.0
